services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000 --app-dir src"

    envVars:
      - key: DATABASE_URL
        value: "postgresql+psycopg2://todos_db_pdyo_user:o2K4wauF3frSXrG5maE5qRTVqkWAHOL3@dpg-d2f3e46mcj7s7388ji5g-a.render.com:5432/todos_db_pdyo
"
"
